version: '3'
services:

  lbc-autoparts-api:
      build:
        context: .
        dockerfile: ./DockerfileApi
      restart: always
      ports:
        - "8002:8000" # Mapear el puerto 5000 del contenedor al puerto 5000 del host
